fail_on_violations: true
javascript:
  enabled: false
eslint:
  enabled: false
  config_file: .eslintrc.json
  version: 6.8.0
tslint:
   enabled: true
scss:
  config_file: .scss-style.yml
  version: 0.57.1 