fail_on_violations: true
javascript:
  enabled: false
eslint:
  enabled: false
tslint:
   enabled: true
   config_file: .tslintrc.json
   versio: 5.9.1
scss:
  config_file: .scss-style.yml
  version: 0.57.1 