sudo: required
dist: xenial
language: java
branches:
  only:
    - master
jdk:
- openjdk8
cache:
  directories:
  - $HOME/.m2
  - muikku-atests/.cargo
addons:
  hosts:
  - dev.muikku.fi
  apt:
    packages:
    - daemon
    - libxi6
    - libgconf-2-4
before_install:
- openssl aes-256-cbc -K $encrypted_f6ca69c00a28_key -iv $encrypted_f6ca69c00a28_iv
  -in travis-encrypted.tar.enc -out travis-encrypted.tar -d
- tar xvf travis-encrypted.tar  
- unset GEM_PATH
- . travis-setenv.sh
install:
- . travis-install.sh
before_script:
- export _JAVA_OPTIONS="-Xmx2048m -Xms512m -Djava.net.preferIPv4Addresses=true -Djava.net.preferIPv4Stack=true"
script:
- . travis-script.sh
after_script:
env:
  global:
  - secure: "aOQe+UgT52sFJnbyeYfdAcgDu910G6G1UKVV2YIOVrjtR0PvYxwztrMOZjnECBtcxAZqLCA57Ao17yuPj0LXP258jeJbufofeSYe7ZBAi5OUQCvp4UsSFMQKsglxgM6xXrpw9jhr9PJXjYpmv5oPtTynjNCQClYCMIFgPiQyXp0="
  - secure: "ZwuYi1pzg9afqyNK08retl3QXDJAC1DStoUZHi2FLTMq6c3txN0d+9wvNDihwElpo25g2t77JvuHTOXIrjPjebZL/XqK502Wqp87EYFP1PCi7GiusDGQU2oLNPwhYdaaxXS8UBVCZnOZ4evpDVkQRw7X/U+qRWfNQ3b2S37YVo4="
  - secure: "ZUGm2KI0kaU+wJAQrZHZYjFIMK3NhzZQOwPui2WtN8r3Fj+u8WCumg8xVTFRV6izy0QTCd5ar9h99Ai5TQ6IO3IxHHZo+M+91m2vt/HHLgn3OX9O+ZeziWBeO1zT8EFhNCKuzNd/3GvnkxGSvH/bd0oTqfLcfQwF/UpQD6HsYlw="
  - secure: "DFuHwiF4OXTuJke1tFfbLma7GbbkQoo3GIGarlWiwA7lhIvgfhXMvHUyyR9VD8+Ftf7ce3U2oa2SaHDIHKEktiSGkh3evgHmyX6mffC0nzDqOl86k+e+IGpwKOut4Cx9ykt7xFxnRtq5OpcLss8NbFbEvCNqjdBcZ9gBp6L/21g="
  matrix:
  - goals=verify run=always perform_release=true it_profile=rest-it findbugs_skip=false use_sc=false
after_success:
- . travis-after-success.sh
notifications:
  webhooks:
    urls:
    - http://build.muikkuverkko.fi/travis.php
    on_success: always
    on_failure: never
    on_start: false
