name: Accessibility checks
on: 
  push:
    branches: [5364-continue-accessibility-testing]
jobs:
  WCAG_check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        testclass: [AnnouncerAT, CommunicatorAT]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
      - name: Build with Maven
        run: mvn install -Pdummy-mail-plugin,pyramus-plugins,elastic-search-plugin,atests-plugin,evaluation-plugin,timed-notifications-plugin,matriculation-plugin -Dfindbugs.skip=true -Dmaven.javadoc.skip=true -Dsource.skip=true
      - name: Set Muikku host
        run: echo "127.0.0.1 dev.muikku.fi" | sudo tee -a /etc/hosts
      - name: Check accessibility
        run: |
            cd muikku-atests
            mvn clean verify -Pwcag -Dit.test=${{ matrix.testclass }}
