name: Announcer sauce tests
on: 
  push:
    branches: [5204-github-actions-testing]
env:
  TUNNEL_ID: ${{env.GITHUB_ACTION}}
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
    - name: Github run Id
      run: echo ${{github.run_id}}
    - name: GITHUB ACTION ENV VAR
      run: echo $GITHUB_ACTION
#      - uses: actions/checkout@v2
#      - name: Set up JDK 1.8
#        uses: actions/setup-java@v1
#        with:
#          java-version: 1.8
#      - name: Cache Maven packages
#        uses: actions/cache@v2
#        with:
#          path: ~/.m2
#          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
#      - name: Build with Maven
#        run: mvn install -Pmongo-log-plugin,dummy-mail-plugin,pyramus-plugins,elastic-search-plugin,atests-plugin,evaluation-plugin,timed-notifications-plugin,matriculation-plugin -Dfindbugs.skip=true -Dmaven.javadoc.skip=true -Dsource.skip=true
#      - name: Set Muikku host
#        run: echo "127.0.0.1 dev.muikku.fi" | sudo tee -a /etc/hosts
#      - name: Setup sauce connect
#        run: |
#            curl https://saucelabs.com/downloads/sc-4.6.2-linux.tar.gz -o saucelabs.tar.gz
#            tar -xzf saucelabs.tar.gz
#            cd sc-*
#            bin/sc -u ${{secrets.SAUCE_USERNAME}} -k ${{secrets.SAUCE_KEY}} --no-ssl-bump-domains=127.0.0.1,localhost,dev.muikku.fi --pidfile=/tmp/sc_client.pid -i ${{env.TUNNEL_ID}}
#            wget --retry-connrefused --no-check-certificate -T 60 localhost:4445
#      - name: Test with chrome
#        run: |
#            cd muikku-atests
#            mvn verify -Dmaven.javadoc.skip=true -Dsource.skip=true -Dit.browser="chrome" -Dit.browser.version="latest" -Dit.browser.resolution="1280x1024" -Dit.platform="Windows 10" -Dit.package="announcer" -Dit.sauce.username=${{secrets.SAUCE_USERNAME}} -Dit.sauce.accessKey=${{secrets.SAUCE_KEY}} -Dit.sauce.tunnelId=${{env.TUNNEL_ID}} -Psauce-it;
#      - name: Shut Down Sauce Connect Tunnel
#        run: kill -9 `cat /tmp/sc_client.pid`
