name: Announcer sauce tests
on: 
  push:
    branches: [5204-github-actions-testing]
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
      - name: Build with Maven
        run: mvn install -Pmongo-log-plugin,dummy-mail-plugin,pyramus-plugins,elastic-search-plugin,atests-plugin,evaluation-plugin,timed-notifications-plugin,matriculation-plugin -Dfindbugs.skip=true -Dmaven.javadoc.skip=true -Dsource.skip=true
      - name: Set Muikku host
        run: echo "127.0.0.1 dev.muikku.fi" | sudo tee -a /etc/hosts
      - uses: saucelabs/sauce-connect-action@master
        with:
          username: ${{ secrets.SAUCE_USERNAME }}
          accessKey: ${{ secrets.SAUCE_KEY }}
          noSSLBumpDomains: "127.0.0.1,localhost,dev.muikku.fi"
          tunnelIdentifier: github-action-muikku-tunnel
          scVersion: 4.6.2
      - name: Test with chrome
        run: |
            cd muikku-atests
            mvn verify -Dmaven.javadoc.skip=true -Dsource.skip=true -Dit.browser="chrome" -Dit.browser.version="latest" -Dit.browser.resolution="1280x1024" -Dit.platform="Windows 10" -Dit.package="announcer" -Dit.sauce.username=${{ secrets.TEST_USERNAME }} -Dit.sauce.accessKey=${{ secrets.TEST_KEY }} -Dit.sauce.tunnelId= -Psauce-it;
