name: Course journal sauce tests
on: 
  repository_dispatch:
    types: [trigger-course-journal-sauce-test]
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.sha }}
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
      - name: Setup sauce connect
        run: |
            curl https://saucelabs.com/downloads/sc-4.6.2-linux.tar.gz -o saucelabs.tar.gz
            tar -xzf saucelabs.tar.gz
            cd sc-*
            bin/sc -u ${{secrets.SAUCE_USERNAME}} -k ${{secrets.SAUCE_KEY}} -i ${{github.run_id}} -f /tmp/sc_ready --no-ssl-bump-domains=127.0.0.1,localhost,dev.muikku.fi --pidfile=/tmp/sc_client.pid &
      - name: Build with Maven
        run: mvn install -Pmongo-log-plugin,dummy-mail-plugin,pyramus-plugins,elastic-search-plugin,atests-plugin,evaluation-plugin,timed-notifications-plugin,matriculation-plugin -Dfindbugs.skip=true -Dmaven.javadoc.skip=true -Dsource.skip=true
      - name: Set Muikku host
        run: echo "127.0.0.1 dev.muikku.fi" | sudo tee -a /etc/hosts
      - name: Check sauce connect
        run: |
              while [ ! -f /tmp/sc_ready ]; do
                echo "Waiting for Sauce Connect..."
                sleep 5;
              done;
      - name: Test with chrome
        run: |
            cd muikku-atests
            mvn verify -Psauce-it -Dmaven.javadoc.skip=true -Dsource.skip=true -Dit.browser="chrome" -Dit.browser.version="latest" -Dit.browser.resolution="1280x1024" -Dit.platform="Windows 10" -Dit.package="course/journal" -Dit.sauce.username=${{secrets.SAUCE_USERNAME}} -Dit.sauce.accessKey=${{secrets.SAUCE_KEY}} -Dit.sauce.tunnelId=${{github.run_id}}
      - name: Read sc_client.pid file
        id: getscpid
        run: echo "::set-output name=scpid::$(cat /tmp/sc_client.pid)"
      - name: Shut Down Sauce Connect Tunnel
        run: |
              kill -2 ${{ steps.getscpid.outputs.scpid }}
              while [ -f /tmp/sc_ready ]; do
                echo "Waiting for Sauce Connect to close..."
                sleep 5;
              done;
      - name: Trigger next workflow
        if: success()
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_GHA_PAT }}
          repository: ${{ github.repository }}
          event-type: trigger-course-management-sauce-test
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'