name: Release
on: 
  push:
    branches: [5233-release-deploy-github-actions]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v2
      # - name: Set up JDK 1.8
      #   uses: actions/setup-java@v1
      #   with:
      #     java-version: 1.8
      # - name: Cache Maven packages
      #   uses: actions/cache@v2
      #   with:
      #     path: ~/.m2
      #     key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
#       - name: Deploy release
#         run: mvn clean deploy --settings ~/.m2/mySettings.xml -Pmongo-log-plugin,jndi-mail-plugin,elastic-search-plugin,evaluation-plugin,timed-notifications-plugin,pyramus-plugins,matriculation-plugin

# ${{ github.event.head_commit.message }} == *"[maven-release-plugin] prepare release"*
# if [[ ($commitmessage == *"[maven-release-plugin] prepare release"*) ]]; then 

      - name: Release or Not
        run: |
            commitmessage="${{ github.event.head_commit.message }}"
            echo "This is the commit message: ${{ github.event.head_commit.message }}"
            if [[ ($commitmessage == *"Merge pull request"*) && ($commitmessage == *"from otavanopisto/devel"*) ]]; then 
              echo "In we are"
            fi;
            echo "Our git ref is: "
            echo ${{ github.ref }}
            echo "or, same here: "
            echo ${GITHUB_REF#refs/heads/}
