name: Release or Deploy
on: 
  push:
    branches: [master]
jobs:
  release:
    env:
      OOM2_USER: ${{secrets.OOM2_USER}}
      OOM2_PASSWORD: ${{secrets.OOM2_PASSWORD}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 20
          ssh-key: ${{ secrets.GA_DEPLOY_KEY }}
          ssh-strict: false
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
      - name: Build with Maven
        run: mvn clean install -Pjndi-mail-plugin,elastic-search-plugin,evaluation-plugin,timed-notifications-plugin,pyramus-plugins,matriculation-plugin
      - name: Prepare maven settings
        run: python prepare-maven.py
      - name: Release or Deploy
        run: ./releaseOrDeploy.sh
        env:
          GA_DEPLOY_KEY: ${{ secrets.GA_DEPLOY_KEY }}
